### ISSUE TITLE
Ошибки компиляция в линуксе

### ISSUE THREAD

**Issue by Moriarty1** [graylor/FastQSP#12]
При компиляции у меня возникли проблемы:

actions.cpp: В функции «void qspAddAction(QSPVariant_, int, QSPLineOfCode_, int, int, QSP_BOOL)»:
actions.cpp:89:15: ошибка: нет декларации «nullptr» в этой области видимости
     imgPath = nullptr;
               ^

Добавил во все хедеры:
`#ifndef nullptr
# include <cstddef>
# define nullptr NULL
# endif`

g++ -c -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -DGIT_VERSION=\"v0.5.1-11-g0d92f5a\" -DNOT_RUBY -D_UNICODE -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/phonon -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/qt4/phonon_compat -I../build/release/moc/gui -o ../build/release/obj/gui/main.o main.cpp
In file included from main.cpp:1:0:
fastqspwindow.h:33:30: fatal error: Phonon/MediaObject: No such file or directory

В fastqspwindow.h заменил 
`#include <Phonon/MediaObject>
# include <Phonon/AudioOutput>`

на
`#include <phonon/MediaObject>
# include <phonon/AudioOutput>`

После этого удачно собралось на ArchLinux x64. Надеюсь внесете необходимые изменения в исходники

**Comment by Moriarty1** [comment]
Все указаные ошибки проявляется только со сборкой qt4. При использовании qt5 все нормально собралось.

**Comment by graylor** [comment]
Добавлены cmake файлы для сборки. С ними все хорошо собирается, на ArchLinux x64 в том числе.
